### ISSUE TITLE
tesseract incompatibility

### ISSUE THREAD

**Issue by arvids-p** [bpieszko/CopyTextFromVideo#1]
OCR.cpp:6:41: error: ‘OEM_LSTM_ONLY’ is not a member of ‘tesseract’ m_api->Init(NULL, language.c_str(), tesseract::OEM_LSTM_ONLY);

tesseract 3.03
 leptonica-1.70
libgif 4.1.6(?) : libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : webp 0.4.0

**Comment by bpieszko** [comment]
Script was developed on tesseract 4.0 and leptonica 1.75.

I'll add informations to readme.
Thanks for letting me know.
